AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alphapulse

  Sample SAM Template for alphapulse

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  # DynamoDB Table for portfolios
  PortfoliosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: alphapulse-portfolios
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: authorizer.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          USER_POOL_ID: us-east-1_OQmaANeqr
          APP_CLIENT_ID: 4niv1oogjm25ln9ummhepvdib3
          REGION: us-east-1

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /hello
            Method: get
            Auth:
              Authorizer: NONE

  PortfolioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: portfolio.lambda_handler
      Runtime: python3.11
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref PortfoliosTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PortfoliosTable
      Events:
        GetPortfolio:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /portfolio
            Method: get
            Auth:
              Authorizer: NONE
        PostPortfolio:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /portfolio
            Method: post
            Auth:
              Authorizer: NONE

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/hello"
  
  PortfolioApi:
    Description: "API Gateway endpoint URL for Prod stage for Portfolio function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/portfolio"
  
  AuthorizerFunction:
    Description: "Lambda Authorizer ARN"
    Value: !GetAtt AuthorizerFunction.Arn
  
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  PortfolioFunction:
    Description: "Portfolio Lambda Function ARN"
    Value: !GetAtt PortfolioFunction.Arn

  PortfoliosTable:
    Description: "DynamoDB Portfolios Table"
    Value: !Ref PortfoliosTable